CREATE TABLE PROJECT (
Project_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
Project VARCHAR(50) NOT NULL,
StartDate DATE,
EndDate DATE,
Priority INT(3),
User_ID INTEGER UNSIGNED NOT NULL,
CONSTRAINT FK_MANAGER_ID FOREIGN KEY (User_ID) REFERENCES USER(User_ID));

CREATE TABLE PARENTTASK(
Parent_ID INT(6) UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
Parent_Task VARCHAR(50) NOT NULL);

CREATE TABLE TASK(
Task_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
Parent_ID INT(6) UNSIGNED NOT NULL,
Project_ID INT(6) UNSIGNED NOT NULL,
User_ID INTEGER UNSIGNED NOT NULL,
Task VARCHAR(50) NOT NULL,
StartDate DATE,
EndDate DATE,
Priority INT(3),
Status VARCHAR(3) NOT NULL,
CONSTRAINT FK_PARENT_ID FOREIGN KEY (Parent_ID) REFERENCES PARENTTASK(Parent_ID),
CONSTRAINT FK_PROJECT_ID FOREIGN KEY (Project_ID) REFERENCES PROJECT(Project_ID),
CONSTRAINT FK_USER_ID FOREIGN KEY (User_ID) REFERENCES USER(User_ID));

CREATE TABLE USER (
User_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Employee_ID VARCHAR(10) NOT NULL);